# Generated by Django 5.1.1 on 2024-09-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climbs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="danger_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="difficulty_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="final_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="logistics_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="technical_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
